### ISSUE TITLE
Cosmos Sync Speed

### ISSUE THREAD

**Issue by faddat** [universelabs/universe-network#11]
**Description**
Cosmos isn't very fast, sync-wise.  Currently, it's possible to sync 10,000 empty blocks in 333 seconds on a macbook pro 2017.  This works out to about 30ms per block.

**Tasks**
- [x] Measure sync speed on Macbook pro
- [ ] Measure on other devices
- [ ] Compare to graphene
- [ ] Compare to Substrate (polkadot)

Any other information you want to share that is relevant to the issue. This might include the lines of code, screenshots, imagery, links, solutions, opinions, feedback, etc.
