### ISSUE TITLE
Send Guy 50,000lyra with memo of an IPFS hash

### ISSUE THREAD

**Issue by faddat** [universelabs/universe-network#9]
**Description**
To test the memo field, send guy 50,000lyra with IPFS hash in the memo field

**Tasks**
- [ ] Find the memo field
- [ ] Buy some ATOMs
- [ ] Learn how to do this on Cosmos

**Comment by faddat** [comment]
There's a small chance I'm dead wrong and there's no memo field on plain coin tx's.... just sayin ;)

:P
